[package]
name = "zkgame-vdf"
version = "0.1.0"
edition = "2021"

[dependencies]
rug = "1.24"
sha2 = "0.10"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8"
num-bigint = "0.4"
num-traits = "0.2"

[dev-dependencies]
criterion = "0.5"
